In [1]:
import pandas as pd
import numpy as np

In [14]:
# loading data
df = pd.read_csv('data.csv', sep=";", low_memory=False)
df = df.dropna()
df.head()

,jobtitle,jobfield,q1,q2,q3,q4,q5,q6,q7,q8,...,scale_e,scale_i,scale_s,scale_n,scale_t,scale_f,scale_j,scale_p,psychotype,satisfied
1,HR manager,Staff and training,1,0,0,1,1,1,1,0,...,16,22,17,16,23,11,22,15,ISTJ,1
2,HR manager,Staff and training,0,0,1,0,0,1,1,0,...,28,6,14,18,20,16,20,15,ENTJ,0
3,HR manager,Staff and training,0,0,1,1,0,1,1,0,...,28,10,22,10,16,14,22,12,ESTJ,1
4,HR manager,Staff and training,0,0,0,0,0,1,1,0,...,24,10,16,17,13,23,31,3,ENFJ,0
5,HR manager,Staff and training,0,1,1,0,0,1,1,1,...,25,12,17,13,23,11,10,25,ESTP,1

In [15]:
# 
cols = df.columns
cols = cols[2:152]
df = df[cols]
df

,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,...,q141,q142,scale_e,scale_i,scale_s,scale_n,scale_t,scale_f,scale_j,scale_p
1,1,0,0,1,1,1,1,0,1,0,...,1,1,16,22,17,16,23,11,22,15
2,0,0,1,0,0,1,1,0,0,1,...,0,1,28,6,14,18,20,16,20,15
3,0,0,1,1,0,1,1,0,0,0,...,0,1,28,10,22,10,16,14,22,12
4,0,0,0,0,0,1,1,0,0,1,...,0,0,24,10,16,17,13,23,31,3
5,0,1,1,0,0,1,1,1,1,0,...,0,1,25,12,17,13,23,11,10,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12617,0,0,0,1,1,1,0,1,0,0,...,0,1,19,16,19,15,16,17,15,17
12618,1,0,1,0,1,1,1,1,1,0,...,0,1,5,32,25,9,11,23,29,8
12619,0,0,0,1,0,0,1,1,0,0,...,1,1,25,14,15,16,18,22,9,25
12620,0,1,1,0,1,1,0,0,0,0,...,1,0,21,16,27,9,30,8,32,2
12621,0,0,1,0,0,1,1,0,1,0,...,0,1,15,18,20,9,28,6,33,6

In [16]:
# finding out correlation between 
corr = df.corr()
corr = corr - np.diag(np.diag(corr))
temp = corr.columns[142:]
corr = corr[temp]
corr = corr[:142]
corr

,scale_e,scale_i,scale_s,scale_n,scale_t,scale_f,scale_j,scale_p
q1,-0.643776,0.646676,0.031868,-0.021185,0.017200,-0.069671,0.013485,-0.022069
q2,-0.112236,0.091986,-0.202422,0.253699,-0.000803,-0.000595,0.016471,-0.008483
q3,0.019254,0.026043,0.163221,-0.198557,0.406434,-0.443394,0.232823,-0.254508
q4,-0.005756,-0.021623,-0.179470,0.205028,-0.114421,0.120994,-0.519517,0.520700
q5,-0.347963,0.367353,-0.093353,0.127429,-0.015629,0.020234,-0.075903,0.079741
...,...,...,...,...,...,...,...,...
q138,0.107298,-0.165185,-0.439593,0.472783,-0.185619,0.194523,-0.273452,0.248870
q139,-0.373588,0.417037,0.275114,-0.283707,0.111004,-0.203788,0.200485,-0.214714
q140,0.073044,-0.042374,0.144069,-0.172176,0.216065,-0.223175,0.413060,-0.460452
q141,0.167112,-0.164826,-0.121390,0.212991,0.047315,-0.045299,-0.072612,0.065247
q142,0.017074,-0.053061,-0.243309,0.173773,0.053675,-0.068567,-0.097569,0.082451

In [17]:
# storing scale labels
scales = cols[142:]
scales

Index(['scale_e', 'scale_i', 'scale_s', 'scale_n', 'scale_t', 'scale_f',
       'scale_j', 'scale_p'],
      dtype='object')

In [18]:
min_max_dict = dict()

In [19]:
for index, row in corr.iterrows():
    min = 999999
    max = -999999
    temp_max = ''
    temp_min = ''
    for scale in scales:
        if row[scale] > max:
            max = row[scale]
            temp_max = scale
        if row[scale] < min:
            min = row[scale]
            temp_min = scale
    min_max_dict[index] = ((temp_min, temp_max), (min, max))

min_max_dict

{'q1': (('scale_e', 'scale_i'), (-0.6437764108169607, 0.6466756261004499)),
 'q2': (('scale_s', 'scale_n'), (-0.2024221820459251, 0.2536987809582383)),
 'q3': (('scale_f', 'scale_t'), (-0.44339390893887437, 0.4064338916817933)),
 'q4': (('scale_j', 'scale_p'), (-0.5195172955952511, 0.5206996907070025)),
 'q5': (('scale_e', 'scale_i'), (-0.3479630720927536, 0.36735312807327364)),
 'q6': (('scale_n', 'scale_s'), (-0.5146795682902188, 0.4607867316821788)),
 'q7': (('scale_f', 'scale_t'), (-0.36841364990526715, 0.41031592513087367)),
 'q8': (('scale_j', 'scale_p'), (-0.5339309761993066, 0.4903434816416694)),
 'q9': (('scale_e', 'scale_i'), (-0.5287250096115682, 0.5246857593916627)),
 'q10': (('scale_s', 'scale_n'), (-0.4758295036147635, 0.49705975675201025)),
 'q11': (('scale_f', 'scale_t'), (-0.5941445140453504, 0.5752030464799602)),
 'q12': (('scale_p', 'scale_j'), (-0.392366487564924, 0.38366685809083584)),
 'q13': (('scale_i', 'scale_e'), (-0.2495469396235054, 0.2983265280235786)),
 'q14': (('scale_s', 'scale_n'), (-0.4167122485512651, 0.4334952920496521)),
 'q15': (('scale_t', 'scale_f'), (-0.3955383866288043, 0.3074163168571731)),
 'q16': (('scale_j', 'scale_p'), (-0.41675691121215885, 0.4267765893877545)),
 'q17': (('scale_i', 'scale_e'), (-0.3725967656543361, 0.46230145036968606)),
 'q18': (('scale_n', 'scale_s'), (-0.31187361948366665, 0.4225531368421903)),
 'q19': (('scale_f', 'scale_t'), (-0.5164222782085723, 0.44229842371088385)),
 'q20': (('scale_j', 'scale_p'), (-0.4765817381198045, 0.5284273281654551)),
 'q21': (('scale_e', 'scale_i'), (-0.5747109598646368, 0.5768462067331335)),
 'q22': (('scale_n', 'scale_s'), (-0.24413988360203065, 0.3340549491372271)),
 'q23': (('scale_f', 'scale_t'), (-0.37156003744649296, 0.4723649543758967)),
 'q24': (('scale_p', 'scale_j'), (-0.3007163122670352, 0.2998936714001626)),
 'q25': (('scale_e', 'scale_i'), (-0.27610669016413764, 0.28626663667402147)),
 'q26': (('scale_s', 'scale_n'), (-0.32301909565743797, 0.3002451852752472)),
 'q27': (('scale_f', 'scale_t'), (-0.38844524317501355, 0.45859310464000164)),
 'q28': (('scale_j', 'scale_p'), (-0.44982402279698186, 0.5041602658333543)),
 'q29': (('scale_e', 'scale_i'), (-0.4258528137790768, 0.4460943662973546)),
 'q30': (('scale_s', 'scale_n'), (-0.5395386414756099, 0.4401953347596678)),
 'q31': (('scale_t', 'scale_f'), (-0.5211503522862884, 0.5303474659706573)),
 'q32': (('scale_j', 'scale_p'), (-0.4522131281121447, 0.47092950915470383)),
 'q33': (('scale_e', 'scale_i'), (-0.3382946947393742, 0.3697690567897009)),
 'q34': (('scale_n', 'scale_s'), (-0.28697357578765553, 0.21055208012109575)),
 'q35': (('scale_t', 'scale_f'), (-0.5151599822342778, 0.5148920420827252)),
 'q36': (('scale_j', 'scale_p'), (-0.5834118094351756, 0.5696799223723779)),
 'q37': (('scale_i', 'scale_e'), (-0.3752472524483325, 0.42865249934043215)),
 'q38': (('scale_n', 'scale_s'), (-0.3649517484812866, 0.2738535907211111)),
 'q39': (('scale_t', 'scale_f'), (-0.4720653674533653, 0.512019734756824)),
 'q40': (('scale_j', 'scale_p'), (-0.5901838244163004, 0.5762042648187237)),
 'q41': (('scale_i', 'scale_e'), (-0.40714377701670673, 0.4065533543447508)),
 'q42': (('scale_s', 'scale_n'), (-0.4061097132857034, 0.40721333735537385)),
 'q43': (('scale_t', 'scale_f'), (-0.4289362755163933, 0.46675859086250426)),
 'q44': (('scale_j', 'scale_p'), (-0.49698850735349653, 0.47718835100440815)),
 'q45': (('scale_e', 'scale_i'), (-0.2990321165889398, 0.37727289797441715)),
 'q46': (('scale_n', 'scale_s'), (-0.418855422609464, 0.5180304398551019)),
 'q47': (('scale_f', 'scale_t'), (-0.4389025356129295, 0.5098789038674638)),
 'q48': (('scale_p', 'scale_j'), (-0.3731746621182794, 0.36500345305104587)),
 'q49': (('scale_e', 'scale_i'), (-0.31433924958122356, 0.2924911744936714)),
 'q50': (('scale_s', 'scale_n'), (-0.5832340841537479, 0.43750221589917676)),
 'q51': (('scale_t', 'scale_f'), (-0.34669186826431153, 0.3360370339767415)),
 'q52': (('scale_j', 'scale_p'), (-0.5006579893541262, 0.47669783218861456)),
 'q53': (('scale_e', 'scale_i'), (-0.20949257753595038, 0.14324242262873962)),
 'q54': (('scale_s', 'scale_f'), (-0.45168781325688256, 0.34123400011731997)),
 'q55': (('scale_t', 'scale_f'), (-0.33241432021606665, 0.3195159052872808)),
 'q56': (('scale_n', 'scale_j'), (-0.3052550650780585, 0.329551845311149)),
 'q57': (('scale_e', 'scale_i'), (-0.36849224545535214, 0.37484374254576397)),
 'q58': (('scale_s', 'scale_n'), (-0.5335145365240784, 0.4665352700605812)),
 'q59': (('scale_t', 'scale_f'), (-0.5245689514301918, 0.4179888827617482)),
 'q60': (('scale_j', 'scale_p'), (-0.5432910272790928, 0.4852189979074136)),
 'q61': (('scale_i', 'scale_e'), (-0.41926381446192235, 0.5080931822208004)),
 'q62': (('scale_s', 'scale_n'), (-0.43043518279475484, 0.449861489707536)),
 'q63': (('scale_f', 'scale_t'), (-0.26237476908555685, 0.39164944062808255)),
 'q64': (('scale_p', 'scale_j'), (-0.2895080367709273, 0.22252361657689185)),
 'q65': (('scale_e', 'scale_i'), (-0.4759643876733713, 0.5305055458181047)),
 'q66': (('scale_s', 'scale_n'), (-0.4725847622765942, 0.36748779533045955)),
 'q67': (('scale_f', 'scale_t'), (-0.38699323508359346, 0.5209146590941467)),
 'q68': (('scale_p', 'scale_j'), (-0.49283119590174806, 0.45913104195561477)),
 'q69': (('scale_e', 'scale_i'), (-0.31903720160227855, 0.36660193631224686)),
 'q70': (('scale_s', 'scale_n'), (-0.2791838237302029, 0.40511093035740114)),
 'q71': (('scale_e', 'scale_t'), (-0.13283409930801715, 0.21320458192678807)),
 'q72': (('scale_j', 'scale_p'), (-0.5138656057942625, 0.5574080455877564)),
 'q73': (('scale_e', 'scale_i'), (-0.3842258399713438, 0.42537644643113476)),
 'q74': (('scale_n', 'scale_s'), (-0.45714385246591455, 0.30307373186570735)),
 'q75': (('scale_e', 'scale_t'), (-0.12424573318139485, 0.16795838755581524)),
 'q76': (('scale_p', 'scale_j'), (-0.38302958798375325, 0.36445254750568334)),
 'q77': (('scale_e', 'scale_i'), (-0.24592626683260027, 0.2435964709901523)),
 'q78': (('scale_s', 'scale_n'), (-0.3189778034675518, 0.244127224292196)),
 'q79': (('scale_f', 'scale_t'), (-0.25001453776606586, 0.24963346315590657)),
 'q80': (('scale_p', 'scale_j'), (-0.3870585148425522, 0.38936555282334373)),
 'q81': (('scale_e', 'scale_i'), (-0.44010433624315354, 0.5097227350099758)),
 'q82': (('scale_i', 'scale_e'), (-0.1989382629102675, 0.1899272195289118)),
 'q83': (('scale_t', 'scale_f'), (-0.47491047929414537, 0.3696883200492713)),
 'q84': (('scale_j', 'scale_p'), (-0.3746303029252497, 0.3306499961222673)),
 'q85': (('scale_e', 'scale_i'), (-0.406589929347136, 0.3105400060791348)),
 'q86': (('scale_s', 'scale_n'), (-0.48519802469039225, 0.4766932904322743)),
 'q87': (('scale_f', 'scale_t'), (-0.2617454381738874, 0.19962188290779942)),
 'q88': (('scale_j', 'scale_p'), (-0.39633400844479316, 0.4650982608036516)),
 'q89': (('scale_e', 'scale_i'), (-0.4211561006768855, 0.33846815709261835)),
 'q90': (('scale_n', 'scale_s'), (-0.3421371114617985, 0.4031433180897123)),
 'q91': (('scale_f', 'scale_t'), (-0.21483236431010028, 0.2584077210834974)),
 'q92': (('scale_j', 'scale_p'), (-0.33974490464732227, 0.4138848057196478)),
 'q93': (('scale_e', 'scale_i'), (-0.3484355139430703, 0.26407849570222264)),
 'q94': (('scale_n', 'scale_s'), (-0.44192678422052195, 0.3388595879084497)),
 'q95': (('scale_f', 'scale_t'), (-0.45509603144851696, 0.43090351742311195)),
 'q96': (('scale_j', 'scale_p'), (-0.28945920584499457, 0.23506583425274458)),
 'q97': (('scale_e', 'scale_i'), (-0.45696346768476864, 0.39912913761655644)),
 'q98': (('scale_n', 'scale_s'), (-0.12117844043941832, 0.19063837620070567)),
 'q99': (('scale_f', 'scale_t'), (-0.2532918057473109, 0.20240600618213211)),
 'q100': (('scale_j', 'scale_e'), (-0.17417375894827858, 0.14039463744669375)),
 'q101': (('scale_e', 'scale_i'), (-0.2728801351475848, 0.22971752668879436)),
 'q102': (('scale_s', 'scale_t'), (-0.24304914186404672, 0.09745883041832203)),
 'q103': (('scale_t', 'scale_f'), (-0.25723823337657054, 0.39965058827105765)),
 'q104': (('scale_j', 'scale_n'), (-0.316132627519374, 0.2745427545273078)),
 'q105': (('scale_e', 'scale_i'), (-0.2249371756116999, 0.1219461963749107)),
 'q106': (('scale_s', 'scale_n'), (-0.3309702178730782, 0.3652095739801687)),
 'q107': (('scale_t', 'scale_f'), (-0.28639581727583163, 0.43590280005652005)),
 'q108': (('scale_j', 'scale_n'), (-0.3479094131190705, 0.2807556872191311)),
 'q109': (('scale_e', 'scale_i'), (-0.38027585632039623, 0.31003905098815426)),
 'q110': (('scale_n', 'scale_j'), (-0.1972236384753949, 0.12128330253271942)),
 'q111': (('scale_t', 'scale_f'), (-0.25347968399789894, 0.35099703086578)),
 'q112': (('scale_e', 'scale_s'), (-0.07344985731731841, 0.0740701388615874)),
 'q113': (('scale_e', 'scale_i'), (-0.2515514118854958, 0.19586201731398445)),
 'q114': (('scale_e', 'scale_f'), (-0.15759104140004232, 0.18436381432039445)),
 'q115': (('scale_t', 'scale_f'), (-0.20591800428963772, 0.2789798683694301)),
 'q116': (('scale_j', 'scale_p'), (-0.5748092207496384, 0.5544905713701013)),
 'q117': (('scale_i', 'scale_e'), (-0.4527996955587748, 0.3415395067859455)),
 'q118': (('scale_f', 'scale_t'), (-0.06782657336303917, 0.08484416151498855)),
 'q119': (('scale_e', 'scale_f'), (-0.04729418425293793, 0.11151176352684845)),
 'q120': (('scale_j', 'scale_f'), (-0.22370250364748273, 0.16229203971236142)),
 'q121': (('scale_e', 'scale_i'), (-0.3425616969129372, 0.40076647441519114)),
 'q122': (('scale_e', 'scale_n'), (-0.11580607121293095, 0.20231390623419743)),
 'q123': (('scale_e', 'scale_i'), (-0.1965812964117897, 0.1945557210387805)),
 'q124': (('scale_f', 'scale_t'), (-0.3113108634223767, 0.32709514811916734)),
 'q125': (('scale_j', 'scale_p'), (-0.349745861880562, 0.3553648300645873)),
 'q126': (('scale_s', 'scale_n'), (-0.2526053707927136, 0.31248628491991176)),
 'q127': (('scale_f', 'scale_t'), (-0.47292647175759567, 0.42080921922515774)),
 'q128': (('scale_p', 'scale_s'), (-0.17739076250678906, 0.11064551325759699)),
 'q129': (('scale_e', 'scale_f'), (-0.1384023701537372, 0.1313077235418988)),
 'q130': (('scale_j', 'scale_p'), (-0.4201109112237592, 0.44129545893581057)),
 'q131': (('scale_i', 'scale_e'), (-0.37083116992496706, 0.3993257047427406)),
 'q132': (('scale_p', 'scale_j'), (-0.2819534135780982, 0.19187567439914516)),
 'q133': (('scale_i', 'scale_e'), (-0.3874920056765209, 0.28806285520367486)),
 'q134': (('scale_s', 'scale_n'), (-0.16908283314568553, 0.24510863704544178)),
 'q135': (('scale_f', 'scale_t'), (-0.29814982967052156, 0.22347230559452197)),
 'q136': (('scale_e', 'scale_i'), (-0.2545067811582494, 0.2580974816113952)),
 'q137': (('scale_i', 'scale_p'), (-0.23658395911394534, 0.19086066369316707)),
 'q138': (('scale_s', 'scale_n'), (-0.4395928804966897, 0.4727826928505449)),
 'q139': (('scale_e', 'scale_i'), (-0.3735875529368473, 0.4170366014726079)),
 'q140': (('scale_p', 'scale_j'), (-0.4604517958072457, 0.4130595265634517)),
 'q141': (('scale_i', 'scale_n'), (-0.16482630569394505, 0.21299082211249937)),
 'q142': (('scale_s', 'scale_n'), (-0.24330905945381462, 0.17377337531949077))}

In [20]:
pairs = [('scale_e', 'scale_i'), ('scale_s', 'scale_n') , ('scale_t', 'scale_f'), ('scale_j', 'scale_p')]

In [21]:
dichotomous = 0
cumulative  = 0
dichotomous_list = []
cumulative_list  = []
for key in min_max_dict:
    for pair in pairs:
        if (min_max_dict[key][0] == pair) or (min_max_dict[key][0] == pair[::-1]):
            dichotomous += 1
            dichotomous_list.append(key)
            break
        
cumulative = 142 - len(dichotomous_list)
for key in min_max_dict:
    if key not in dichotomous_list:
        cumulative_list.append(key)

print('dichotomous questions =', dichotomous_list)
print('no. of dichotomous questions =', dichotomous)
print('cumulative questions =', cumulative_list)
print('no. of cumulative questions =', cumulative)

dichotomous questions = ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'q16', 'q17', 'q18', 'q19', 'q20', 'q21', 'q22', 'q23', 'q24', 'q25', 'q26', 'q27', 'q28', 'q29', 'q30', 'q31', 'q32', 'q33', 'q34', 'q35', 'q36', 'q37', 'q38', 'q39', 'q40', 'q41', 'q42', 'q43', 'q44', 'q45', 'q46', 'q47', 'q48', 'q49', 'q50', 'q51', 'q52', 'q53', 'q55', 'q57', 'q58', 'q59', 'q60', 'q61', 'q62', 'q63', 'q64', 'q65', 'q66', 'q67', 'q68', 'q69', 'q70', 'q72', 'q73', 'q74', 'q76', 'q77', 'q78', 'q79', 'q80', 'q81', 'q82', 'q83', 'q84', 'q85', 'q86', 'q87', 'q88', 'q89', 'q90', 'q91', 'q92', 'q93', 'q94', 'q95', 'q96', 'q97', 'q98', 'q99', 'q101', 'q103', 'q105', 'q106', 'q107', 'q109', 'q111', 'q113', 'q115', 'q116', 'q117', 'q118', 'q121', 'q123', 'q124', 'q125', 'q126', 'q127', 'q130', 'q131', 'q132', 'q133', 'q134', 'q135', 'q136', 'q138', 'q139', 'q140', 'q142']
no. of dichotomous questions = 124
cumulative questions = ['q54', 'q56', 'q71', 'q75', 'q100', 'q102', 'q104', 'q108', 'q110', 'q112', 'q114', 'q119', 'q120', 'q122', 'q128', 'q129', 'q137', 'q141']
no. of cumulative questions = 18

In [27]:
scales_dict = dict()
for scale in scales:
    scales_dict[scale] = 0

scales_dict

{'scale_e': 0,
 'scale_i': 0,
 'scale_s': 0,
 'scale_n': 0,
 'scale_t': 0,
 'scale_f': 0,
 'scale_j': 0,
 'scale_p': 0}

In [28]:
for index, row in df.iterrows():
    for q in min_max_dict.keys():
        if q in dichotomous_list:
            if int(row[q]) == 0:
                scales_dict[min_max_dict[q][0][0]] += 1
            else:
                scales_dict[min_max_dict[q][0][1]] += 1
    break

scales_dict

{'scale_e': 19,
 'scale_i': 18,
 'scale_s': 13,
 'scale_n': 15,
 'scale_t': 19,
 'scale_f': 12,
 'scale_j': 16,
 'scale_p': 12}

In [24]:
# e_i_scale = ('scale_e', 'scale_i')
# s_n_scale = ('scale_s', 'scale_n')
# t_f_scale = ('scale_t', 'scale_f')
# j_p_scale = ('scale_j', 'scale_p')